### ISSUE TITLE
Add support for pluggable transports (obfsproxy, meek, scramblesuit, etc)

### ISSUE THREAD

**Issue by jlund** [mtigas/iOS-OnionBrowser#43]
https://www.torproject.org/projects/obfsproxy.html.en

Ideally this functionality would be based on the new ScrambleSuit pluggable transport that is resistant to active probing attacks, but supporting the obfs3 pluggable transport would still be highly useful.

This would allow Onion Browser to be used in countries that are employing DPI to block/detect Tor connections, which are the countries that need Tor the most.

**Comment by mtigas** [comment]
Jumping back into this ol’ ticket.

Been working on this for the past few weeks, aiming to get [obfs4proxy](https://github.com/Yawning/obfs4) in, which supports obfs2, obfs3, obfs4, scramblesuit, and meek_lite (which is a version of [meek](https://trac.torproject.org/projects/tor/wiki/doc/meek)). The work is spread out a bit between [the iObfs repo](https://github.com/mtigas/iObfs) and the [Onion Browser iobfs branch](https://github.com/OnionBrowser/iOS-OnionBrowser/tree/iobfs).

[Recently got it to work](https://lists.mayfirst.org/pipermail/guardian-dev/2016-April/004731.html) and have some [decent test output](https://gist.github.com/mtigas/f1b9a3a8befa6f60d517eb2340f3cdd4) from iObfs+Onion Browser running on a device. So this should be good for the next release — have a bit of cleanup & documenting to do, so probably around May 1.

**Comment by mtigas** [comment]
iObfs integration made it in when 1.6 was released this month.

https://github.com/mtigas/iOS-OnionBrowser/releases/tag/v1.6.0

**Comment by jlund** [comment]
This is excellent news! Nice work on this! I'm adding support to Streisand now.

**Comment by jlund** [comment]
[Done!](https://github.com/jlund/streisand/commit/15993fe27533515c38c1f9619b7d19ca92983e17) Thanks again to everyone involved who helped make this happen. It's a huge feature.
