### ISSUE TITLE
Bridge Entry Screen "Continue Anyway" Doesn't Work

### ISSUE THREAD

**Issue by teor2345** [mtigas/iOS-OnionBrowser#65]
When I don't want to enter any bridges on the bridge entry screen, and click "Save" or "Cancel", the "Continue Anyway" button returns me to the bridge entry screen. I have to restart the app to exit the bridge entry screen.

Steps To Reproduce:
1. Open Onion Browser
2. Open Settings
3. Open Bridge Entry Screen
4. Tap "Save" or "Cancel"
5. Tap "Continue Anyway"

**Comment by mtigas** [comment]
(This was fixed at some point during the 1.6 cycle.)
