### ISSUE TITLE
OpenSSL download path has changed

### ISSUE THREAD

**Issue by Tuzr** [mtigas/iOS-OnionBrowser#70]
I found that , in build-libssl.sh , at line 87
`curl -O http://www.openssl.org/source/openssl-${VERSION}.tar.gz`
This url does't exist from now.

It should be 
`curl -O https://www.openssl.org/source/old/${VERSION}/openssl-${VERSION}.tar.gz`

The correct url is https://www.openssl.org/source/old/1.0.2g/openssl-1.0.2g.tar.gz (Version 1.0.2g)

**Comment by mtigas** [comment]
Updated in master.

* Looks like the paths now use HTTPS all the time (yay).

* The latest version of OpenSSL actually does still live at the previous URL pattern; the script will continue to use that by default.

  Older patch-revisions do need that `/old/` bit added -- and I noticed that it's `/old/1.0.2/openssl-1.0.2g.tar.gz` (note that directory drops the patch-revision letter). For now, I've added commented-out lines for the alternate URLs (for the tarball and the PGP signature).
